services:
  postgres:
    image: 'postgres:16'
    environment:
      POSTGRES_DB: digital-wallet
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    ports:
      - '5432:5432'
  rabbitmq:
    image: "rabbitmq:3.8.6-management"
    ports:
      - '5672:5672'
      - '15672:15672'