spring:
  application:
    name: digital-wallet
  datasource:
    url: jdbc:postgresql://localhost:5432/digital-wallet
    username: user
    password: password
  jpa:
    show-sql: true
  ### RABBIT ###
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    br.com.akj: DEBUG

### ACTUATOR ###
# set to always show the details at health check endpoint
management:
  endpoint.health.show-details: always
# set the resources to be exposed
  endpoints.web.exposure.include: health,info,metrics

### LIQUIBASE ###
liquibase:
  enabled: true

integration:
  api:
    authorizer:
      host: https://run.mocky.io
      v3:
        basePath: /v3
        authorize: /5794d450-d2e2-4412-8131-73d0293ac1cc
    notification:
      host: https://run.mocky.io
      v3:
        basePath: /v3
        send: /54dc2cf1-3add-45b5-b5a9-6bf7e7f1f4a6

message:
  exchange: digital_wallet::tx
  notification:
    queue:
      route: rk::send_notification
      name: digital_wallet::send_notification::q
      dlq:
        ttl: 5000
        route: rk::send_notification::dlq
        name: digital_wallet::send_notification::dlq
        retries: 5
      plq:
        route: rk::send_notification::plq
        name: digital_wallet::send_notification::plq